---
- hosts: jodconverter
  become: true
  roles:
    - role: java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk

  vars:
    source: "/etc/ansible/projects/sei/sources"

  tasks:
  - name: Copy jodconverter
    unarchive:
      src: "{{ source }}/jodconverter/jodconverter-tomcat-2.2.2.zip"
      dest: "/opt"

  - name: Copy xml files for Protocolos
    copy:
      src: "{{ source }}/jodconverter/tomcat"
      dest: "/etc/init.d"
      owner: root
      group: root
      mode: u=rwx,g=r,o=r

  handlers:
  - name: Config tomcat service
    service:
      name: tomcat
      state: started
      enabled: yes

  environment:
    http_proxy: "http://proxy.mj.gov.br:3128"
    https_proxy: "http://proxy.mj.gov.br:3128"
    ftp_proxy: "http://proxy.mj.gov.br:3128"
    no_proxy: "localhost,127.0.0.1"
