---
- hosts: webserver
  become: true
  roles:
    - role: php
      remove_php: true
      webserver: httpd
      php_version: php56
      repository: remi
      create_phpinfo: true

      php_modules:
        - cli
        - common
        - devel
        - fpm
        - gd
        - ldap
        - mbstring
        - mcrypt
        - mysqlnd
        - opcache
        - pdo
        - pear
        - process
        - xml

  environment:
    http_proxy: "http://proxy.mj.gov.br:3128"
    https_proxy: "http://proxy.mj.gov.br:3128"
    ftp_proxy: "http://proxy.mj.gov.br:3128"
