---
- hosts: webserver
  become: true
  roles:
    -  role: php
  vars:
    remove_php: true
    php_version: php70
    repository: remi
    php_modules:
      - cli
      - common
      - devel
      - fpm
      - gd
      - ldap
      - mbstring
      - mcrypt
      - mysqlnd
      - opcache
      - pdo
      - pear
      - process
      - xml

  environment:
    http_proxy: "http://proxy.mj.gov.br:3128"
    https_proxy: "http://proxy.mj.gov.br:3128"
    ftp_proxy: "http://proxy.mj.gov.br:3128"
    no_proxy: "localhost,127.0.0.1"
