---
- hosts: webserver
  become: true
  roles:
    - role: php
      php_enablerepo: "remi"
      php_packages_state: "installed"
      php_install_recommends: yes
      php_webserver_daemon: "httpd"
      php_memory_limit: "128M"
      php_max_execution_time: "90"
      php_upload_max_filesize: "256M"
      php_packages:
        - php5.6
        - php5.6-cli
        - php5.6-common
        - php5.6-devel
        - php5.6-gd
        - php5.6-mbstring
        - php5.6-pdo
        - php5.6-pecl-apcu
        - php5.6-xml

  environment:
    http_proxy: "http://proxy.mj.gov.br:3128"
    https_proxy: "http://proxy.mj.gov.br:3128"
    ftp_proxy: "http://proxy.mj.gov.br:3128"
