---
- hosts: webserver
  become: true
  roles:
    - role: php
      php_enablerepo: "remi"
      php_webserver_daemon: "httpd"
      php_memory_limit: "128M"
      php_max_execution_time: "90"
      php_upload_max_filesize: "256M"
      php_packages:
        - php56
        - php56-cli
        - php56-common
        - php56-devel
        - php56-gd
        - php56-mbstring
        - php56-pdo
        - php56-pecl-apcu
        - php56-xml

  environment:
    http_proxy: "http://proxy.mj.gov.br:3128"
    https_proxy: "http://proxy.mj.gov.br:3128"
    ftp_proxy: "http://proxy.mj.gov.br:3128"
