---
- hosts: nginx
  become: true
  roles:
    - role: nginx
      nginx_sites:
        sei.mj.gov.br:
          - listen *:80
          - server_name "sei.mj.gov.br"
          - access_log /var/log/nginx/access.log combined
          - error_log /var/log/nginx/error.log
          - location / {
                  proxy_set_header        Host $http_host;
                  proxy_set_header        X-Real-IP $remote_addr;
                  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_pass              http://lb.sei.mj.gov.br;
            }
      nginx_configs:
        upstream:
          - upstream lb.sei.mj.gov.br {
                   ip_hash;
                   server 10.10.12.109;
            }
environment:
  http_proxy: "http://proxy.mj.gov.br:3128"
  https_proxy: "http://proxy.mj.gov.br:3128"
  ftp_proxy: "http://proxy.mj.gov.br:3128"
