---
- hosts: solr
  become: true
  roles:
    - role: java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk

    - role: solr
      solr_version: "6.1.0"
      solr_create_user: true
      solr_user: solr
      solr_port: "8983"
      solr_xms: "256M"
      solr_xmx: "512M"
      solr_cores:
        - sei-bases-conhecimento
        - sei-protocolos
        - sei-publicacoes

  tasks:
    - copy: Base Publicacoes
      src: source/sei-bases-conhecimento/*
      dest: /var/solr/data/sei-bases-conhecimento/conf/
      owner: solr
      group: solr
      mode: u=rw,g=r,o=r

    - copy: Protocolos
      src: source/sei-protocolos/*
      dest: /var/solr/data/sei-protocolos/conf/
      owner: solr
      group: solr
      mode: u=rw,g=r,o=r

    - copy: Publicacoes
      src: source/sei-publicacoes/*
      dest: /var/solr/data/sei-protocolos/conf/
      owner: solr
      group: solr
      mode: u=rw,g=r,o=r

  environment:
    http_proxy: "http://proxy.mj.gov.br:3128"
    https_proxy: "http://proxy.mj.gov.br:3128"
    ftp_proxy: "http://proxy.mj.gov.br:3128"
    no_proxy: "localhost,127.0.0.1"
